# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
solver_wrapper <- function() {
    invisible(.Call(`_RFATODE_solver_wrapper`))
}

#' @export
explicit_RK <- function() {
    invisible(.Call(`_RFATODE_explicit_RK`))
}

